### ISSUE TITLE
Allow to manually split speed ratio between clients

### ISSUE THREAD

**Issue by btTeddy** [itschasa/speedrr#26]
Example usage scenario:

Cleint1 5000x of very small torrents (e.g pdf) that rarely gets downloaded/uploaded

Client2 500x of large torrents that gets constantly downloaded/uploaded

At the moment, ratio will be set 10:1 prioritising client1 that actually doesn't need it, client2 will be choked.

Brief suggestion based on config
```
clients:
  - speed_limiting_algorithm: manual # possible options: automatic|manual

  client1:
  - type: qbittorrent
    url: <webui_url>
    username: <username>
    password: <password>
    https_verify: true
    percentage_of_max_permited_upload_speed: 20%
    percentage_of_max_permited_download_speed: 30%

  client2:
  - type: qbittorrent
    url: <webui_url>
    username: <username>
    password: <password>
    https_verify: true
    percentage_of_max_permited_upload_speed: 60%
    percentage_of_max_permited_download_speed: 50%
```
